---
- name: Hostname
  debug: msg="hostname {{ansible_hostname}} inventory name  {{ansible_hostname}}"

- name: nginx start
  become: yes
  service:
      name: nginx
      state: started

- name: nginx reload
  become: yes
  service:
      name: nginx
      state: reloaded

- name: restart nginx
  service: name=nginx state=restarted