---
- name: installation serveurs web 
  hosts: web
  remote_user: root
  tasks:
    - name: installation zsh et htop
      apt: 
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items: 
        - zsh
        - htop
...

